### BASE URL
@baseUrl = http://localhost:3000

### AUTH TOKEN
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmYTNjMzdhOC01MGE1LTQzNzgtYmZhNi00ZmRlZWU0ZmZkZjIiLCJlbWFpbCI6ImpvbmF0aGFubXVsaW5nZW13YW5kaUBnbWFpbC5jb20iLCJyb2xlIjoiQURNSU4iLCJpYXQiOjE3NjM3NjgxNDYsImV4cCI6MTc2Mzg1NDU0Nn0.HQzpxGkOd2F4rJJL3d0YfoEuXvFhufDxv55O9ar3I4Q
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjN2Q0NzVmZS01Y2Q5LTRjYjktOWM1OS03NmVlZmNhNWIzZjAiLCJlbWFpbCI6ImpvbmF0aGFubXdhbmRpQGdtYWlsLmNvbSIsInJvbGUiOiJMRUFSTkVSIiwiaWF0IjoxNzYzNzY4MTcxLCJleHAiOjE3NjM4NTQ1NzF9.AtiXWd2eHJN-xKGXp37LGY9hPlGqInIL9rTN3b2uFgs

#######################################################
### 1. CREATE LESSON (Admin)
#######################################################
POST {{baseUrl}}/lessons
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "title": "Understanding God’s Grace",
  "content": "This lesson explores the meaning, power, and impact of God's grace in a believer's life...",
  "questions": [
    {
      "question": "How would you define God’s grace in your own words?"
    },
    {
      "question": "Why is grace essential for salvation?"
    },
    {
      "question": "Can grace and works coexist in Christian life?"
    }
  ]
}


#######################################################
### 2. GET ALL LESSONS
#######################################################
GET {{baseUrl}}/lessons
Authorization: Bearer {{token2}}


#######################################################
### 3. GET SINGLE LESSON
#######################################################
GET {{baseUrl}}/lessons/77212c30-0b91-469f-acf6-5bc40fb345dd
Authorization: Bearer {{token2}}


#######################################################
### 4. UPDATE LESSON
#######################################################
PATCH {{baseUrl}}/lessons/77212c30-0b91-469f-acf6-5bc40fb345dd
Authorization: Bearer {{{{token2}}}}
Content-Type: application/json

{
  "title": "Introduction to Christian Faith"
}


#######################################################
### 5. DELETE LESSON
#######################################################
DELETE {{baseUrl}}/lessons/LESSON_ID_HERE
Authorization: Bearer {{token}}

#######################################################
### 6. STUDENT: ASK QUESTION ABOUT A LESSON
#######################################################

POST {{baseUrl}}/lessons/answers/c7d475fe-5cd9-4cb9-9c59-76eefca5b3f0/21d59676-b591-4972-8bc6-45c7f3284492
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "answer": "This is my answer to the lesson question."
}



#######################################################
### 6. STUDENT: ASK QUESTION ABOUT A LESSON
#######################################################
POST {{baseUrl}}/lessons/77212c30-0b91-469f-acf6-5bc40fb345dd/questions/c7d475fe-5cd9-4cb9-9c59-76eefca5b3f0
Authorization: Bearer {{token2}}
Content-Type: application/json

{
  "question": "I didn't understand the part about Abraham's faith, please explain?"
}


#######################################################
### 7. ADMIN: GET ALL STUDENT QUESTIONS
#######################################################
GET {{baseUrl}}/lessons/questions/all
Authorization: Bearer {{token}}


#######################################################
### 8. ADMIN: GET QUESTIONS BY LESSON
#######################################################
GET {{baseUrl}}/lessons/77212c30-0b91-469f-acf6-5bc40fb345dd/questions
Authorization: Bearer {{token}}


#######################################################
### 9. ADMIN: GET QUESTIONS BY STUDENT
#######################################################
GET {{baseUrl}}/lessons/student/c7d475fe-5cd9-4cb9-9c59-76eefca5b3f0/questions
Authorization: Bearer {{token}}


#######################################################
### 10. ADMIN reply to student answers
#######################################################

POST {{baseUrl}}/lessons/answers/reply/:answerId'
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "answer": "This is the admin response to your question."
}
